# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ca677a75dcea94e90e41faa4a316aed74d5a844f21efef82e073486b8a15eb8fbdd62125399b2d4879642df60afb7651f4f1a0e8029cfe73a64c965bc3adf79

test:
  secret_key_base: b5d573914a814a3c609e93a0dc205aaaa5cd087111c803f775726eb1b3f2ebf0256502f22f69f2630d6cd643ae3421d8591ee43ebd733a9b53b55d05d87d6726

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
